# Generated by Django 5.1.2 on 2025-02-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_customuser_username_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('design', 'Art/Design'), ('marketing', 'Sale/Marketing'), ('finance', 'Finance'), ('education', 'Education/Training'), ('healthcare', 'Healthcare'), ('science', 'Science'), ('food_services', 'Food Services')], max_length=50),
        ),
    ]
