# Generated by Django 5.1.2 on 2024-11-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_resumeprofile_experience_education_resumeskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='description',
            new_name='work_description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='end_year',
            new_name='work_end_year',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='start_year',
            new_name='work_start_year',
        ),
    ]
