# Generated by Django 5.1.2 on 2024-11-11 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_resumeprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resume_profiles', to='web_app.customuser'),
        ),
    ]
