# Generated by Django 5.1.2 on 2024-11-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_resumeprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeprofile',
            name='per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
