# Generated by Django 5.1.2 on 2024-11-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_category_remove_job_is_remote_job_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, choices=[('technolgy', 'Technology'), ('design', 'Art/Design'), ('marketing', 'Sale/Marketing'), ('finance', 'Finance'), ('education', 'Education/Training'), ('healthcare', 'Healthcare'), ('science', 'Science'), ('food_services', 'Food Services')], help_text='Select the category that best describes the job.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
