# Generated by Django 5.1.2 on 2024-11-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_alter_job_category_alter_job_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
